name: Docker Java Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in the repository
      run: |
        ls -R  # List all files to ensure DockerDemo.java exists

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker-container
        buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
        install: false
        use: true
        cleanup: true

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/a18_oussamahachemi_final_1270 .

    - name: Run Docker container
      run: |
        docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/a18_oussamahachemi_final_1270

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/a18_oussamahachemi_final_1270
